-- MySQL Script generated by MySQL Workbench
-- Wed Jan 27 18:07:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`uzivatel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`uzivatel` (
  `iduzivatel` INT(11) NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(64) NOT NULL,
  `prijmeni` VARCHAR(64) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `heslo` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`iduzivatel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produkt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produkt` (
  `idprodukt` INT NOT NULL AUTO_INCREMENT,
  `jmenoProdukt` VARCHAR(45) NULL,
  `popisProdukt` VARCHAR(255) NULL,
  `cenaProdukt` INT NULL,
  `imageProdukt` VARCHAR(45) NULL,
  `kategorieProdukt` VARCHAR(45) NULL,
  `znackaProdukt` VARCHAR(45) NULL,
  `barvaProdukt` VARCHAR(45) NULL,
  `pohlaviProdukt` VARCHAR(45) NULL,
  PRIMARY KEY (`idprodukt`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kosik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kosik` (
  `uzivatel_iduzivatel` INT(11) NOT NULL,
  `produkt_idprodukt` INT NOT NULL,
  `velikost` VARCHAR(45) NULL,
  PRIMARY KEY (`uzivatel_iduzivatel`, `produkt_idprodukt`),
  INDEX `fk_uzivatel_has_produkt_produkt1_idx` (`produkt_idprodukt` ASC) VISIBLE,
  INDEX `fk_uzivatel_has_produkt_uzivatel1_idx` (`uzivatel_iduzivatel` ASC) VISIBLE,
  CONSTRAINT `fk_uzivatel_has_produkt_uzivatel1`
    FOREIGN KEY (`uzivatel_iduzivatel`)
    REFERENCES `mydb`.`uzivatel` (`iduzivatel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uzivatel_has_produkt_produkt1`
    FOREIGN KEY (`produkt_idprodukt`)
    REFERENCES `mydb`.`produkt` (`idprodukt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`objednavky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`objednavky` (
  `idobjednavky` INT NOT NULL AUTO_INCREMENT,
  `uzivatel_iduzivatel` INT(11) NOT NULL,
  `datum` DATE NULL,
  PRIMARY KEY (`idobjednavky`),
  INDEX `fk_objednavky_uzivatel1_idx` (`uzivatel_iduzivatel` ASC) VISIBLE,
  CONSTRAINT `fk_objednavky_uzivatel1`
    FOREIGN KEY (`uzivatel_iduzivatel`)
    REFERENCES `mydb`.`uzivatel` (`iduzivatel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`objednavky_has_produkt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`objednavky_has_produkt` (
  `objednavky_idobjednavky` INT NOT NULL,
  `produkt_idprodukt` INT NOT NULL,
  `velikost` VARCHAR(45) NULL,
  PRIMARY KEY (`objednavky_idobjednavky`, `produkt_idprodukt`),
  INDEX `fk_objednavky_has_produkt_produkt1_idx` (`produkt_idprodukt` ASC) VISIBLE,
  INDEX `fk_objednavky_has_produkt_objednavky1_idx` (`objednavky_idobjednavky` ASC) VISIBLE,
  CONSTRAINT `fk_objednavky_has_produkt_objednavky1`
    FOREIGN KEY (`objednavky_idobjednavky`)
    REFERENCES `mydb`.`objednavky` (`idobjednavky`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_objednavky_has_produkt_produkt1`
    FOREIGN KEY (`produkt_idprodukt`)
    REFERENCES `mydb`.`produkt` (`idprodukt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
